### PR TITLE
Fix minimist vulnerability

### PR DESCRIPTION
**Pull request by crism**
This fixes the vulnerability in issue #22 and also a few other things found with `npm audit`.

### CODE REVIEW

**Comment by crism** [comment]
This was against `master` instead of `development`.

**Comment by crism** [comment]
Reopening per suggestion from owners.

**Comment by BillFarber** [comment]
This PR is limited to updates to the dependency versions. Looks good to me.

**Comment by grtjn** [comment]
Thanks for showing interest in Grove after so long! I ran npm update against the dev branch, and managed to solve all vulernabilities. I merged dev to master, so I think this PR is redundant now, as well as those other automatic once, which will probably auto-close soon.

**Comment by crism** [comment]
Thanks, @grtjn!

**Pull request closed without merging**
